export const HCMC_STREET_SOURCE = {
  name: "WeRent HCMC street seed v1",
  note:
    "Lightweight starter index. Can be extended from official open datasets published at data.hochiminhcity.gov.vn.",
  reviewedSources: [
    "https://data.hochiminhcity.gov.vn/",
    "https://opendata.hochiminhcity.gov.vn/",
  ],
};

export const HCMC_STREET_GROUPS = [
  {
    street: "Lê Thị Riêng",
    placements: [
      ["Quận 1"],
      ["Quận 3"],
      ["Quận 10"],
      ["Quận 12"],
      ["Huyện Hóc Môn"],
    ],
  },
  { street: "Trường Chinh", placements: [["Quận Tân Bình"], ["Quận Tân Phú"], ["Quận 12"]] },
  { street: "Lê Văn Quới", placements: [["Quận Bình Tân"], ["Quận Tân Phú"]] },
  { street: "Đồng Khởi", placements: [["Quận 1"]] },
  { street: "Lê Duẩn", placements: [["Quận 1"]] },
  { street: "Nguyễn Trãi", placements: [["Quận 1"], ["Quận 5"]] },
  { street: "Trần Hưng Đạo", placements: [["Quận 1"], ["Quận 5"]] },
  { street: "Cách Mạng Tháng 8", placements: [["Quận 1"], ["Quận 3"], ["Quận 10"], ["Quận Tân Bình"]] },
  { street: "Điện Biên Phủ", placements: [["Quận 1"], ["Quận 3"], ["Quận Bình Thạnh"]] },
  { street: "Võ Văn Kiệt", placements: [["Quận 1"], ["Quận 5"], ["Quận 6"], ["Quận 8"], ["Huyện Bình Chánh"]] },
  { street: "Nguyễn Huệ", placements: [["Quận 1"]] },
  { street: "Lê Lợi", placements: [["Quận 1"]] },
  { street: "Hàm Nghi", placements: [["Quận 1"]] },
  { street: "Pasteur", placements: [["Quận 1"], ["Quận 3"]] },
  { street: "Nam Kỳ Khởi Nghĩa", placements: [["Quận 1"], ["Quận 3"]] },
  { street: "Hai Bà Trưng", placements: [["Quận 1"], ["Quận 3"]] },
  { street: "Nguyễn Thị Minh Khai", placements: [["Quận 1"], ["Quận 3"]] },
  { street: "Võ Văn Tần", placements: [["Quận 3"]] },
  { street: "Nguyễn Đình Chiểu", placements: [["Quận 1"], ["Quận 3"]] },
  { street: "Lý Tự Trọng", placements: [["Quận 1"]] },
  { street: "Tôn Đức Thắng", placements: [["Quận 1"], ["Quận Bình Thạnh"]] },
  { street: "Đinh Tiên Hoàng", placements: [["Quận 1"], ["Quận Bình Thạnh"]] },
  { street: "Nguyễn Bỉnh Khiêm", placements: [["Quận 1"]] },
  { street: "Bùi Viện", placements: [["Quận 1"]] },
  { street: "Phạm Ngũ Lão", placements: [["Quận 1"], ["Quận Gò Vấp"]] },
  { street: "Cô Giang", placements: [["Quận 1"]] },
  { street: "Cô Bắc", placements: [["Quận 1"]] },
  { street: "Nguyễn Văn Cừ", placements: [["Quận 1"], ["Quận 5"]] },
  { street: "Hùng Vương", placements: [["Quận 5"], ["Quận 10"]] },
  { street: "An Dương Vương", placements: [["Quận 5"], ["Quận 6"], ["Quận 8"], ["Quận Bình Tân"]] },
  { street: "Trần Phú", placements: [["Quận 5"]] },
  { street: "Hồng Bàng", placements: [["Quận 5"], ["Quận 6"]] },
  { street: "Châu Văn Liêm", placements: [["Quận 5"]] },
  { street: "Hải Thượng Lãn Ông", placements: [["Quận 5"]] },
  { street: "Nguyễn Tri Phương", placements: [["Quận 5"], ["Quận 10"]] },
  { street: "Lý Thường Kiệt", placements: [["Quận 10"], ["Quận 11"], ["Quận Tân Bình"]] },
  { street: "3 Tháng 2", placements: [["Quận 10"], ["Quận 11"]] },
  { street: "Thành Thái", placements: [["Quận 10"]] },
  { street: "Sư Vạn Hạnh", placements: [["Quận 10"]] },
  { street: "Tô Hiến Thành", placements: [["Quận 10"]] },
  { street: "Bắc Hải", placements: [["Quận 10"]] },
  { street: "Lữ Gia", placements: [["Quận 11"]] },
  { street: "Lạc Long Quân", placements: [["Quận 11"], ["Quận Tân Bình"], ["Quận Tân Phú"]] },
  { street: "Âu Cơ", placements: [["Quận 11"], ["Quận Tân Bình"], ["Quận Tân Phú"]] },
  { street: "Minh Phụng", placements: [["Quận 6"], ["Quận 11"]] },
  { street: "Hậu Giang", placements: [["Quận 6"]] },
  { street: "Kinh Dương Vương", placements: [["Quận 6"], ["Quận Bình Tân"]] },
  { street: "Phạm Văn Chí", placements: [["Quận 6"]] },
  { street: "Nguyễn Văn Linh", placements: [["Quận 7"], ["Huyện Bình Chánh"], ["Huyện Nhà Bè"]] },
  { street: "Nguyễn Hữu Thọ", placements: [["Quận 7"], ["Huyện Nhà Bè"]] },
  { street: "Huỳnh Tấn Phát", placements: [["Quận 7"], ["Huyện Nhà Bè"]] },
  { street: "Nguyễn Thị Thập", placements: [["Quận 7"]] },
  { street: "Hoàng Quốc Việt", placements: [["Quận 7"]] },
  { street: "Lâm Văn Bền", placements: [["Quận 7"]] },
  { street: "Nguyễn Lương Bằng", placements: [["Quận 7"]] },
  { street: "Phạm Thế Hiển", placements: [["Quận 8"]] },
  { street: "Tạ Quang Bửu", placements: [["Quận 8"]] },
  { street: "Dương Bá Trạc", placements: [["Quận 8"]] },
  { street: "Bến Vân Đồn", placements: [["Quận 4"]] },
  { street: "Khánh Hội", placements: [["Quận 4"]] },
  { street: "Hoàng Diệu", placements: [["Quận 4"]] },
  { street: "Nguyễn Tất Thành", placements: [["Quận 4"]] },
  { street: "Xô Viết Nghệ Tĩnh", placements: [["Quận Bình Thạnh"]] },
  { street: "Bạch Đằng", placements: [["Quận Bình Thạnh"], ["Quận Tân Bình"]] },
  { street: "Đinh Bộ Lĩnh", placements: [["Quận Bình Thạnh"]] },
  { street: "Ung Văn Khiêm", placements: [["Quận Bình Thạnh"]] },
  { street: "Nguyễn Hữu Cảnh", placements: [["Quận Bình Thạnh"]] },
  { street: "Nơ Trang Long", placements: [["Quận Bình Thạnh"]] },
  { street: "Phan Đăng Lưu", placements: [["Quận Bình Thạnh"], ["Quận Phú Nhuận"]] },
  { street: "Nguyễn Xí", placements: [["Quận Bình Thạnh"]] },
  { street: "Nguyễn Gia Trí", placements: [["Quận Bình Thạnh"]] },
  { street: "Vạn Kiếp", placements: [["Quận Bình Thạnh"]] },
  { street: "Phan Văn Trị", placements: [["Quận Bình Thạnh"], ["Quận Gò Vấp"]] },
  { street: "Quang Trung", placements: [["Quận Gò Vấp"], ["Quận 12"]] },
  { street: "Nguyễn Oanh", placements: [["Quận Gò Vấp"]] },
  { street: "Nguyễn Kiệm", placements: [["Quận Gò Vấp"], ["Quận Phú Nhuận"]] },
  { street: "Lê Đức Thọ", placements: [["Quận Gò Vấp"]] },
  { street: "Lê Văn Thọ", placements: [["Quận Gò Vấp"]] },
  { street: "Phạm Văn Đồng", placements: [["Quận Gò Vấp"], ["Quận Bình Thạnh"], ["TP. Thủ Đức"]] },
  { street: "Nguyễn Văn Lượng", placements: [["Quận Gò Vấp"]] },
  { street: "Hoàng Văn Thụ", placements: [["Quận Phú Nhuận"], ["Quận Tân Bình"]] },
  { street: "Phan Xích Long", placements: [["Quận Phú Nhuận"]] },
  { street: "Huỳnh Văn Bánh", placements: [["Quận Phú Nhuận"]] },
  { street: "Nguyễn Văn Trỗi", placements: [["Quận Phú Nhuận"]] },
  { street: "Cộng Hòa", placements: [["Quận Tân Bình"]] },
  { street: "Trương Công Định", placements: [["Quận Tân Bình"]] },
  { street: "Út Tịch", placements: [["Quận Tân Bình"]] },
  { street: "Phổ Quang", placements: [["Quận Tân Bình"], ["Quận Phú Nhuận"]] },
  { street: "Hồng Hà", placements: [["Quận Tân Bình"]] },
  { street: "Trường Sơn", placements: [["Quận Tân Bình"]] },
  { street: "Tân Kỳ Tân Quý", placements: [["Quận Tân Phú"], ["Quận Bình Tân"]] },
  { street: "Tân Quý", placements: [["Huyện Bình Chánh"], ["Quận Tân Phú"]] },
  { street: "Nguyễn Quý Yêm", placements: [["Quận Bình Tân"]] },
  { street: "Phạm Quý Thích", placements: [["Quận Tân Phú"]] },
  { street: "Lũy Bán Bích", placements: [["Quận Tân Phú"]] },
  { street: "Hòa Bình", placements: [["Quận Tân Phú"], ["Quận 11"]] },
  { street: "Vườn Lài", placements: [["Quận Tân Phú"], ["Quận 12"]] },
  { street: "Nguyễn Sơn", placements: [["Quận Tân Phú"]] },
  { street: "Bình Long", placements: [["Quận Tân Phú"], ["Quận Bình Tân"]] },
  { street: "Tây Thạnh", placements: [["Quận Tân Phú"]] },
  { street: "Tên Lửa", placements: [["Quận Bình Tân"]] },
  { street: "Vành Đai Trong", placements: [["Quận Bình Tân"]] },
  { street: "Mã Lò", placements: [["Quận Bình Tân"]] },
  { street: "Đường Số 10", placements: [["Quận Bình Tân"], ["Quận 7"], ["TP. Thủ Đức"]] },
  { street: "Dương Thị Mười", placements: [["Quận 12"]] },
  { street: "Hà Huy Giáp", placements: [["Quận 12"]] },
  { street: "Tô Ký", placements: [["Quận 12"], ["Huyện Hóc Môn"]] },
  { street: "Lê Văn Khương", placements: [["Quận 12"], ["Huyện Hóc Môn"]] },
  { street: "Song Hành", placements: [["Quận 12"], ["TP. Thủ Đức"]] },
  { street: "Mai Chí Thọ", placements: [["TP. Thủ Đức"]] },
  { street: "Đồng Văn Cống", placements: [["TP. Thủ Đức"]] },
  { street: "Nguyễn Cơ Thạch", placements: [["TP. Thủ Đức"]] },
  { street: "Đỗ Xuân Hợp", placements: [["TP. Thủ Đức"]] },
  { street: "Nguyễn Xiển", placements: [["TP. Thủ Đức"]] },
  { street: "Xa Lộ Hà Nội", placements: [["TP. Thủ Đức"]] },
  { street: "Võ Nguyên Giáp", placements: [["TP. Thủ Đức"]] },
  { street: "Kha Vạn Cân", placements: [["TP. Thủ Đức"]] },
  { street: "Tô Ngọc Vân", placements: [["TP. Thủ Đức"]] },
  { street: "Quốc Hương", placements: [["TP. Thủ Đức"]] },
  { street: "Nguyễn Văn Hưởng", placements: [["TP. Thủ Đức"]] },
  { street: "Lương Định Của", placements: [["TP. Thủ Đức"]] },
  { street: "Nguyễn Duy Trinh", placements: [["TP. Thủ Đức"]] },
  { street: "Lê Văn Việt", placements: [["TP. Thủ Đức"]] },
  { street: "Man Thiện", placements: [["TP. Thủ Đức"]] },
  { street: "Nguyễn Ảnh Thủ", placements: [["Quận 12"], ["Huyện Hóc Môn"]] },
  { street: "Nguyễn Thị Sóc", placements: [["Huyện Hóc Môn"]] },
  { street: "Đặng Thúc Vịnh", placements: [["Huyện Hóc Môn"]] },
  { street: "Nguyễn Văn Bứa", placements: [["Huyện Hóc Môn"]] },
  { street: "Tỉnh Lộ 10", placements: [["Quận Bình Tân"], ["Huyện Bình Chánh"]] },
  { street: "Quốc Lộ 1A", placements: [["Quận 12"], ["Quận Bình Tân"], ["Huyện Bình Chánh"]] },
  { street: "Quốc Lộ 13", placements: [["TP. Thủ Đức"]] },
  { street: "Quốc Lộ 22", placements: [["Quận 12"], ["Huyện Hóc Môn"], ["Huyện Củ Chi"]] },
  { street: "Nguyễn Thị Tú", placements: [["Quận Bình Tân"], ["Huyện Bình Chánh"]] },
  { street: "Vĩnh Lộc", placements: [["Quận Bình Tân"], ["Huyện Bình Chánh"]] },
  { street: "Đinh Đức Thiện", placements: [["Huyện Bình Chánh"]] },
  { street: "Đoàn Nguyễn Tuân", placements: [["Huyện Bình Chánh"]] },
  { street: "Nguyễn Văn Linh", placements: [["Huyện Bình Chánh"], ["Quận 7"], ["Huyện Nhà Bè"]] },
  { street: "Lê Văn Lương", placements: [["Quận 7"], ["Huyện Nhà Bè"]] },
  { street: "Nguyễn Bình", placements: [["Huyện Nhà Bè"]] },
  { street: "Huỳnh Tấn Phát", placements: [["Huyện Nhà Bè"], ["Quận 7"]] },
  { street: "Nguyễn Văn Tạo", placements: [["Huyện Nhà Bè"]] },
  { street: "Đào Sư Tích", placements: [["Huyện Nhà Bè"]] },
  { street: "Nguyễn Văn Khạ", placements: [["Huyện Củ Chi"]] },
  { street: "Tỉnh Lộ 8", placements: [["Huyện Củ Chi"]] },
  { street: "Nguyễn Thị Rành", placements: [["Huyện Củ Chi"]] },
  { street: "Võ Văn Bích", placements: [["Huyện Củ Chi"]] },
  { street: "Cần Thạnh", placements: [["Huyện Cần Giờ"]] },
  { street: "Duyên Hải", placements: [["Huyện Cần Giờ"]] },
  { street: "Rừng Sác", placements: [["Huyện Cần Giờ"], ["Huyện Nhà Bè"]] },
];
